### ISSUE TITLE
Add link to this project

### ISSUE THREAD

**Issue by RicoSuter** [Jusas/NSwag.AzureFunctionsV2#1]
Great project - well documented and code looks nice, thank you! 

Can you ping me if you think it makes sense to put a link to this repo on the NSwag readme file?

You probably won’t be able to always update this library when a new nswag version is released... maybe it would make sense to test whether it’s possible to reference a newer nswag version in the function project - if this picks up the latest version (given no breaking changes) it would make sense to describe this in your wiki...

**Comment by Jusas** [comment]
@RicoSuter Thank you! You have a pretty rapid release cycle so yeah, I wouldn't be able to keep up with my limited time. But you can link to this project, sure! I was thinking of maybe adding a compatibility tag to my readme/wiki to clarify the version of NSwag this project has been tested with.

The core dependencies are NSwag.Core and NSwag.SwaggerGeneration, as long as the public APIs of those don't change in any destructive manner, things should work. Therefore this project should be just fine when applying minor patches. However it's possible that the APIs don't change but the behavior/specifications behind them do change - in which case it's important to run the full test suite to see that everything functions as expected. I recall I started development with v12.0.10 and when I upgraded to v12.0.14 there were quite a few changes, including a few (although minor) breaking API changes - so even if we're talking about patch level updates, some things can occasionally slip in.

So go ahead, you can add a link to this project, I'll be updating my readme and wiki to reflect which version of NSwag this has been tested against.

**Comment by Jusas** [comment]
Readme and Wiki updated. Closing this issue.

**Comment by RicoSuter** [comment]
NSwag wiki updated.

**Comment by RicoSuter** [comment]
> I recall I started development with v12.0.10 and when I upgraded to v12.0.14 there were quite a few changes, including a few (although minor) breaking API changes - so even if we're talking about patch level updates, some things can occasionally slip in.

I know that I'm on a quite fast release cycle and do not adhere to semver - for my convenience I use the same version for all libraries and I really try to not break APIs. You are using quite "low-level" APIs (most are just using the CLI and settings) and thus there might be some patch-level breaks... if I'd go with semver I'd be at version 100 right now :-)

But I'd say that NSwag.Core and NSwag.SwaggerGeneration are quite stable and should not see breaking changes... an exception might be further support of OpenAPI 3 which might require some more changes in these libs...

**Comment by RicoSuter** [comment]
Question: Do you already support OpenAPI 3 (i.e. expose SchemaType in the settings and also check this in the generator)? Not sure if this is even necessary in your case as lots of stuff is already handled internally in the model...

**Comment by Jusas** [comment]
> 
> 
> Question: Do you already support OpenAPI 3 (i.e. expose SchemaType in the settings and also check this in the generator)? Not sure if this is even necessary in your case as lots of stuff is already handled internally in the model...

SchemaType is present via inheritance, AzureFunctionsV2ToSwaggerGeneratorSettings inherits SwaggerGeneratorSettings. I'm not very familiar with OpenAPI 3 spec and my OperationParameterProcessor was built on the basis of the WebAPI - and quite frankly I'm not quite sure what OpenAPI 3 brings with it. So I guess the answer is both yes and no. It is there, but the behavior may not be quite there. The only references to this setting are basically two blocks of code, boiling down to this:
```
// if it's a path parameter
if (_settings.SchemaType == SchemaType.Swagger2)
    operationParameter.IsNullableRaw = false;
```
and
```
// otherwise...
if (_settings.SchemaType == SchemaType.OpenApi3)
{
    operationParameter.IsNullableRaw = null;
}
```
And you're right, most of OpenAPI 3 related stuff is actually handled outside the SwaggerGenerator, in NSwag.Core.

**Comment by RicoSuter** [comment]
Ok then, I'll try to keep as much magic in core so that it just works... but maybe at some point it makes sense that you inherit from SwaggerGenerator (base class) and we move as much logic into this class so that we don't have duplicate code... for now it's fine. Thanks for your work.

**Comment by Jusas** [comment]
Not sure we understood each other right - I am indeed using SwaggerGenerator for the work, following the example of WebApiToSwaggerGenerator.

> most of OpenAPI 3 related stuff is actually handled outside the SwaggerGenerator, in NSwag.Core.

In this sentence the SwaggerGenerator I was speaking of was actually my own class, AzureFunctionsV2ToSwaggerGenerator, and I was referring to OpenAPI 3 related stuff being outside that, in your Core library :)

**Comment by RicoSuter** [comment]
Yes, you are probably right - i probably need to recheck your code 🙂 

Anyway, everything is fine - will ping you if there are any issues, updates or upcoming changes
