### ISSUE TITLE
How do I add a response header 

### ISSUE THREAD

**Issue by SpeedOfSpin** [Jusas/NSwag.AzureFunctionsV2#2]
Hi

I have a number of headers that I return in the response such as X-RateLimit-Limit etc.
How do I go about describing these to nswag. 
I would like to produce the following output for the response

thanks!

```
 responses:
        '200':
          x-nullable: true
          description: OK result
          headers:
            X-RateLimit-Limit:
              schema:
                type: integer
              description: Request limit per hour.
          schema:
            type: array
            items:
              $ref: '#/definitions/MediaResponse'
```

**Comment by RicoSuter** [comment]
Add them in a custom operation processor? 

https://github.com/RicoSuter/NSwag/wiki/Document-Processors-and-Operation-Processors

**Comment by Jusas** [comment]
> 
> 
> Add them in a custom operation processor?
> 
> https://github.com/RicoSuter/NSwag/wiki/Document-Processors-and-Operation-Processors

Should work, yeah.

**Comment by SpeedOfSpin** [comment]
Thanks guys! I will give it a go. It looks like it will do the job

thanks again :-)
