### ISSUE TITLE
Function with POST trigger and POST body model does not show up

### ISSUE THREAD

**Issue by RicoSuter** [Jusas/NSwag.AzureFunctionsV2#6]
This function 

```csharp
[FunctionName("PostWebhookAsync")]
[SwaggerResponse(200, typeof(WebhookResponse), Description = "OK result")]
public async Task<IActionResult> PostWebhookAsync(
    [HttpTrigger(AuthorizationLevel.Function, "post", Route = "tenants/{tenantId}/webhooks")] WebhookBodyRequest request,
    [NotNull]string tenantId, ILogger log)
{
```

does not show up in the spec. 

If i change `WebhookBodyRequest request` to `HttpRequest request` then it shows up. Am I missing something?

**Comment by Jusas** [comment]
Yeah, that's because currently the discovery works by first trying to search for a parameter with the type HttpRequest and if it finds it, proceeds to get the trigger attribute from it:

```
            var httpRequestParameter = method.GetParameters()
                .SingleOrDefault(x => x.ParameterType.Name == "HttpRequest");
            var httpTriggerAttribute = httpRequestParameter?.GetCustomAttributes()
                .SingleOrDefault(x => x.GetType().Name == "HttpTriggerAttribute");
```

The main thing discovery wise is to find the HttpTriggerAttribute, and I suppose we could just check for any parameter having that attribute as that's mostly what matters.

**Comment by RicoSuter** [comment]
Ok, so there is currently no workaround or way to use this function at the moment?

**Comment by Jusas** [comment]
I'm afraid not, until a change to the discovery method is made.

**Comment by Jusas** [comment]
Fixing this as we speak.
If you don't mind me asking, what's the use case? I haven't realized you could use something else than the HttpRequest in the signature.

**Comment by RicoSuter** [comment]
If you use an own class instead of HttpRequest for a POST function it will deserialize the JSON body to this class...

**Comment by Jusas** [comment]
Alright, the issue should now have been fixed and v1.1.3 should be available from Nuget momentarily.

**Comment by RicoSuter** [comment]
Thank you very much. Ill try it out tomorrow.

**Comment by RicoSuter** [comment]
Looks good now. Thank you.
