### ISSUE TITLE
Project test names are a bit long

### ISSUE THREAD

**Issue by bigmat** [Jusas/NSwag.AzureFunctionsV2#8]
Hello,

Can you rename the test projects please ?
This is quite long if you do not work at the root of your drive : NSwag.AzureFunctionsV2\src\NSwag.SwaggerGeneration.AzureFunctionsV2.Tests.HttpExtensionsApp.Startup\obj\Debug\netstandard2.0\NSwag.SwaggerGeneration.AzureFunctionsV2.Tests.HttpExtensionsApp.Startup.assets.cache

I had the move my repo in order to build, vs failed :
Path: obj\Debug\netstandard2.0\NSwag.SwaggerGeneration.AzureFunctionsV2.Tests.HttpExtensionsApp.Startup.AssemblyInfoInputs.cache exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.

**Comment by Jusas** [comment]
Yeah, it's pretty amazing that Windows still has this arcane limitation - which is probably why you often see quite short paths in project root paths.

Shortening these to Tests.Http... (41 characters saved) would probably give some wiggle room. I'll have a look.

Edit: to be precise, there should be a setting to overcome the 260 char limitation but I recall Nuget at least can't live with it and cannot overcome the limitation, so it isn't very helpful.

**Comment by Jusas** [comment]
Done.

**Comment by bigmat** [comment]
Thank you

**Comment by Jusas** [comment]
@bigmat Just noticed that I didn't of course fix the actual folder names... this is now done as well. Sorry about that 😕

**Comment by bigmat** [comment]
repo updated, working perfectly :slightly_smiling_face:
